# Generated by Django 5.1.3 on 2024-11-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
